Feat: 멘토링 코드 리뷰(~ 11/28)
prgrms-web-devcourse-final-project/WEB1_2_Inte11i9ence_BE pull request #22
Opened 2024-11-28 10:48 UTC by YooJHyun

## #️⃣연관된 이슈

## ☑️ PR 유형

-  [x] 새로운 기능 추가
-  [x] 코드 리팩토링

## 📝 작업 내용

11/28까지 작성한 코드입니다. 코드 리뷰 감사합니다

## ✅ 피드백 반영사항

## 💬 리뷰 요구사항
<!-- 리뷰어가 중점적으로 봐주면 좋을 것 같은 부분이 있다면 작성해주세요. ->

2024-11-28 17:04 UTC, Account-4-Review requested changes
중복되는 리뷰 포인트가 많이 나올 것 같아서, 일단 1차적으로 커트합니다.

- 공통화 될 가능성이 있는 코드 범위가 꽤 많은 것 같아요.
- 전반적으로 가변 dto 를 사용하는데, 가능하면 전부 불변으로 바꾸는걸 강력히 권장합니다.
- 코드 포매터 적용해 주세요.

2024-11-28 17:04 UTC, Account-4-Review commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +        if (!isLiked) {
좋아요 -> 좋아요 취소를 하면 unlikesKey는 redis에 남겠죠?

2024-11-28 17:04 UTC, Account-4-Review commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +            likes += redisTemplate.opsForSet().size(likesKey);
?

2024-11-28 17:04 UTC, Account-4-Review commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +        if (Boolean.TRUE.equals(redisTemplate.opsForSet().isMember(likesKey, memberId))) {
이걸 굳이 `Boolean.TRUE.equals()` 를 껴서 써야 할 필요가 있나요?

2024-11-29 01:31 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/controller/MemberController.java
> +    public ResponseEntity<?> getCurrentMember(Authentication authentication) {
반영했습니다 ! :)

2024-11-29 01:36 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/controller/ApiResponse.java
> +        return new ApiResponse<>(message, result);
해당 응답 래퍼는 삭제하는 것으로 반영하였습니다!

2024-11-29 02:04 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/dto/MemberResponseDTO.java
> +@NoArgsConstructor
반영했습니다!

2024-11-29 02:04 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/entity/Member.java
> +    private LocalDateTime createdAt;//회원가입 날짜
반영했습니다!

2024-11-29 02:06 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/entity/Member.java
> +    @Column(nullable = false)
반영했습니다!

2024-11-29 02:12 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/oauth2/config/CorsMvcConfig.java
> +                .allowedOrigins("http://localhost:3000");
반영했습니다 :)

2024-11-29 02:37 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/service/MemberService.java
> +@Transactional
반영했습니다!

2024-11-29 02:41 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/controller/MemberController.java
> +    public ResponseEntity<?> putCurrentMember(Authentication authentication, @RequestBody MemberRequestDTO memberRequestDTO) {
반영했습니다!

2024-11-29 02:59 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/entity/Member.java
> +    private String role;            //유저 권한
반영했습니다!

2024-11-29 03:38 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/oauth2/service/CustomOAuth2UserService.java
> +            Member member = Member.builder()
반영했습니다! :)

2024-11-29 03:38 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/oauth2/service/CustomOAuth2UserService.java
> +                    .role("ROLE_USER")
반영했습니다 ~:)

2024-11-29 03:40 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/oauth2/service/CustomOAuth2UserService.java
> +        System.out.println(oAuth2User);
반영 완료했습니다!

2024-11-29 06:24 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/oauth2/service/CustomOAuth2UserService.java
> +        OAuth2Response oAuth2Response = null;
반영 완료했습니다!

2024-11-29 06:26 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/entity/Member.java
> +@NoArgsConstructor
반영 완료했습니다!

2024-11-29 07:16 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/dto/MemberDTO.java
> +public class MemberDTO {    //페이로드용 DTO
setter를 없애는 쪽으로 반영했습니다!

2024-11-29 07:20 UTC, ghtndl commented on src/main/java/com/prgrmsfinal/skypedia/member/service/MemberService.java
> +        session.disableFilter("withdrawnFilter");
try/catch로 반영완료했습니다!

2024-11-29 12:30 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +                switch (order) {
Switch문이 필요한 경우 enhanced-switch문을 사용하도록 하겠습니다.
파일 목록 조회, 검색 기능은 QueryDSL 적용하여 동적 쿼리로 작성하려고 합니다!

2024-11-29 12:41 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +        if (!isLiked) {
아.. unlikesKey를 남기지 않도록 코드를 개선하겠습니다.
생각해본 방법은 다음과 같은데요.
- TTL을 설정하여 일정 시간 이후 자동으로 제거한다.
- 좋아요를 취소하면 해당 unlikesKey를 완전히 삭제하도록 처리한다.

2024-11-29 12:41 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +            likes += redisTemplate.opsForSet().size(likesKey);
헉! `+=` 이 아닌 `-=` 입니다! ㅠ

2024-11-29 12:48 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/post/service/PostServiceImpl.java
> +        if (Boolean.TRUE.equals(redisTemplate.opsForSet().isMember(likesKey, memberId))) {
아. boolean 타입으로 받으면 true false로 반환되며, 
null 값이 존재하지 않으므로, 생각해보니 Boolean.TRUE는 과한 것 같습니다.

2024-11-29 12:49 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/global/exception/CommonException.java
> +    private int code;
넵! 알겠습니다. HttpStatus로 교체하겠습니다.

2024-11-29 12:52 UTC, juwon-code commented on src/main/java/com/prgrmsfinal/skypedia/global/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(CommonException.class)
Valid 관련 예외들과 DB에 데이터 입출력 시 발생할 수 있는 예외들을
파악하여 처리 할 예정입니다.
로깅 작업은 PostSchedular.class를 제외한 클래스에서 작업할 예정에 있습니다.

2024-12-01 03:09 UTC, closed without merging